<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VSANKAR2" name="com.miscellaneous.ErrorHandlingTests" tests="2" failures="2" timestamp="1 Feb 2019 12:52:33 GMT" time="694.872" errors="0">
  <testcase name="verify_error_msg_on_fpcontent_down" time="157.962" classname="com.miscellaneous.ErrorHandlingTests">
    <failure type="java.lang.AssertionError" message="expected [gnbukihnxrcgnmnxhxgliwgqqzpiph] but found [sorry to break the news, but this page is no longer available.]">
      <![CDATA[java.lang.AssertionError: expected [gnbukihnxrcgnmnxhxgliwgqqzpiph] but found [sorry to break the news, but this page is no longer available.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.util.WrapperFunctions.assertEqualsIgnoreCase(WrapperFunctions.java:1581)
	at com.miscellaneous.ErrorHandlingTests.verify_error_msg_on_fpcontent_down(ErrorHandlingTests.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify_error_msg_on_fpcontent_down -->
  <testcase name="verify_error_msg_cache_content_on_pages" time="536.910" classname="com.miscellaneous.ErrorHandlingTests">
    <failure type="java.lang.AssertionError" message="By.id: art_state LISTBOX NOT FOUND. TEST FAILED.">
      <![CDATA[java.lang.AssertionError: By.id: art_state LISTBOX NOT FOUND. TEST FAILED.
	at org.testng.Assert.fail(Assert.java:94)
	at com.util.WrapperFunctions.selectByVisibleText(WrapperFunctions.java:822)
	at com.pageobjects.JoomlaConfigPage.publish_article(JoomlaConfigPage.java:162)
	at com.miscellaneous.ErrorHandlingTests.verify_error_msg_cache_content_on_pages(ErrorHandlingTests.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify_error_msg_cache_content_on_pages -->
</testsuite> <!-- com.miscellaneous.ErrorHandlingTests -->
